### ISSUE TITLE
[FEATURE] no linux support

### ISSUE THREAD

**Issue by HoseanRC** [IdleCollect/Miner.Releases.Public#6]
there is no Linux version of the miner
mining on Linux is kinda faster when using no Desktop Environment than windows
basically there are less running processes and more supported platforms for it

please add a Linux version

**Comment by Xevier1** [comment]
Unfortunately due to the naturally small userbase of community linux users coupled with the fact that those users have on average a worse GPU than windows users, it is quite a bit out of our scope as a business to dedicate time to creating a Linux version while the app is still in the very early stages.

We will most likely look into this in a few months time once we have our roadmap fully fleshed out
In the mean time, if you wanted to continue to use IdleCollect (as it's often a better choice than any other 'do it for you miners' due to the low fees, efficient mining, etc) then i would suggest using dual boots, your performance will suffer but it is better than nothing.

Thanks for your feedback.
